### ISSUE TITLE
Bug: obtaining negative Fst values

### ISSUE THREAD

**Issue by ne1s0n** [lpembleton/StAMPP#4]
I obtain negative Fst, which should be impossible (Fst is strictly defined in [0,1]).
I was able to reproduce it on the demo code:

```
data(potato.mini, package="StAMPP")
potato.freq <- stamppConvert(potato.mini, "r")

#Calculate pairwise Fst values between each population
potato.fst <- stamppFst(potato.freq, 100, 95, 10) #this works as expected


#reduced example, only three markers
smallpotato.freq <- stamppConvert(potato.mini[,1:7], "r")
smallpotato.fst <- stamppFst(potato.freq2, 100, 95, 10)
View(smallpotato.fst$Fsts) #negative values in Fst!
```

**Comment by lpembleton** [comment]
Thanks for your query. Negative Fsts typically can just be viewed as 0. Yes in a well-represented dataset, Fst values are bounded between 0 and 1, however negative values are not impossible. They usually result when the sample size or loci size is too small/not representative (such as your example). This isn't a bug and will occur in other programs that calculate Fsts. Some programs will also recode negative values to 0 before outputting the results to the user. StAMPP doesn't do this as it will impact the CI calculations.

**Comment by ne1s0n** [comment]
>They usually result when the sample size or loci size is too small/not representative (such as your example). 

I obtain negative values also with my own data (~1700 SNPs, 54 samples, 18 populations) which I attach, anonymized:
[sample_data_neg_fst.csv.gz](https://github.com/lpembleton/StAMPP/files/15305402/sample_data_neg_fst.csv.gz)

You can reproduce the negative results with:

```
sample_freqs = read.csv(file.path(outfolder, 'sample_data_neg_fst.csv.gz'), row.names = 1)
Fst = stamppFst(geno = sample_freqs, nboots = 1000)
View(Fst$Fsts) #all negative Fst values
```

This is also strange because I measured the population differentiation with different analyses and some populations are indeed quite different, but using  'stamppFst()` I would conclude that there is no differentiation whatsoever

**Comment by lpembleton** [comment]
So I think this is because for the vast majority of your loci there isn't any genetic differentiation, the allele frequencies are largely the same between and within populations. 

```
loci_var <- apply(sample_freqs[,-c(1:5)], 2, var)
plot(sort(loci_var))
```

This is masking any true differentiation that exists at other loci and for the Fst calculation is indicating that there is equal or more variation within your populations than between. 

So the negative/zero values I would say are correct based on the input data, however, I would always suggest doing some level of filtering of loci. If you filter with the following and rerun the Fst calculation you will start to get more of a story around your Fst values, some populations appearing different and some not. You will need to decide on what min variance cut off to apply. 

```
idx <- which(loci_var >= 0.015) + 5
sample_freq_filtered <- sample_freq[,c(1:5, idx)]
Fst <- stamppFst(geno = sample_freq_filtered)
```

I'm interested in what type of genotyping data you have, given you are using frequencies for individuals, and whether there is any changes you could make to the preprocessing genotyping steps to get more resolution for some of those loci. Or maybe those loci are reasonably fixed across populations. I understand you might not be able to share this info publicly over GitHub though.

**Comment by ne1s0n** [comment]
Sure I'll write you in private
